before:
  hooks:
    - go mod download
builds:
  - id: kubectl-envsubst
    binary: kubectl-envsubst
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

checksum:
  name_template: checksums.txt

archives:
  - builds:
      - kubectl-envsubst
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: "false"
    format: tar.gz
    files:
      - LICENSE
