version: 2

before:
  hooks:
    - go mod download

builds:
  - id: kubectl-envsubst
    main: ./cmd/kubectl-envsubst
    binary: kubectl-envsubst
    ldflags:
      - -s -w
      - -X github.com/hashmap-kz/kubectl-envsubst/pkg/version.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

checksum:
  name_template: checksums.txt

archives:
  - builds:
      - kubectl-envsubst
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: "false"
    formats: ["tar.gz"]
    files:
      - LICENSE

nfpms:
  - file_name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    maintainer: alexey.zh
    homepage: "https://github.com/hashmap-kz/kubectl-envsubst"
    description: "Substitute environment variable placeholders in Kubernetes manifests before applying them."
    license: "Apache-2.0"
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/kubectl-envsubst/copyright
        file_info:
          mode: 0644

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
