---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app ${PROJECT_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: *app
  template:
    metadata:
      labels:
        app: *app
    spec:
      containers:
        - name: *app
          image: $IMAGE_NAME:$IMAGE_TAG
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
          resources: {}
      volumes:
        - name: nginx-html
          configMap:
            name: nginx-index
