---
apiVersion: v1
kind: Service
metadata:
  name: &app ${PROJECT_NAME}
  labels:
    app: *app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 32501
      name: *app
  selector:
    app: *app
