---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kubectl-envsubst-8e4eeb15301847f5b51a24cc595b5f87
  name: my-app
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/logs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
