---
apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: kubectl-envsubst-8e4eeb15301847f5b51a24cc595b5f87
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
