---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ${APP_NAMESPACE}
  name: ${APP_NAME}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/logs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
