---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: kubectl-envsubst-tmpns-testmix
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      serviceAccountName: my-app
      containers:
        - name: my-app
          image: nginx
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: my-app
            - secretRef:
                name: my-app
