---
apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: kubectl-envsubst-integration-tests-ns-2
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
