---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${CI_PROJECT_NAME}
data:
  ${CI_PROJECT_ROOT_NAMESPACE}-${CI_COMMIT_REF_NAME}: |
    server {
        listen 80;
        server_name localhost;
        return 301 https://$server_name$request_uri;
        server_tokens off;
        access_log off;
        error_log off;
    }
    server {
        listen 443 ssl;
        server_name localhost;
        access_log /var/log/nginx/access.log json_combined;
        error_log /var/log/nginx/error.log warn;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        location /api/ {
            proxy_pass http://gateway-service-http:8080/api/;
        }
    }
