---
name: ci
on:
  - push
jobs:
  ci_job:
    name: test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # docs: https://github.com/helm/kind-action
      - name: Prepare kind cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: kubectl-envsubst
          install_only: true
          kubectl_version: "v1.31.1"

      - name: Run unit tests
        run: make test

      - name: Generate coverage report
        run: make test-cov

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      # Note: makefile stages: build/install/kind-setup/test-integration
      - name: Run integration tests
        run: make test-integration

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          install-only: true

      - name: Check goreleaser
        run: make snapshot
